// <auto-generated />
using InstitutoAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InstitutoAPI.Migrations
{
    [DbContext(typeof(EstudianteDbContext))]
    partial class EstudianteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InstitutoAPI.Models.Autor", b =>
                {
                    b.Property<int>("AutorID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido");

                    b.Property<string>("Nombre");

                    b.HasKey("AutorID");

                    b.ToTable("T_Autor");
                });

            modelBuilder.Entity("InstitutoAPI.Models.Estudiante", b =>
                {
                    b.Property<int>("EstudianteID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("AutorID")
                        .HasColumnType("int");

                    b.Property<string>("Carrera")
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Escuela")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("EstudianteID");

                    b.HasIndex("AutorID");

                    b.ToTable("T_Estudiante");
                });

            modelBuilder.Entity("InstitutoAPI.Models.Estudiante", b =>
                {
                    b.HasOne("InstitutoAPI.Models.Autor", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
